services:
  rockbot-backend:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_USER=rockbot
      - DB_PASSWORD=rockbotpassword
      - DB_DATABASE=rockbotdb
      - DB_HOST=rockbot-db
      - TV_SOURCE_BASE_URL=https://api4.thetvdb.com/v4
      - TV_SOURCE_API_KEY=${TV_DB_API_KEY}
      - TV_SOURCE_PIN=${TV_DB_PIN}
  rockbot-db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=rockbot
      - POSTGRES_PASSWORD=rockbotpassword
      - POSTGRES_DB=rockbotdb
    ports:
      - "5432:5432"
    volumes:
      - ./migration:/etc/migration

volumes:
  migration: